Fixes issue #152 - error with creating wandb artifact
huggingface/lerobot pull request #172
Opened 2024-05-10 18:43 UTC by AshisGhosh

## What this does
Quick fix for #152. 

Unnecessary if the string name for the datasets change. More discussion here: f80902b 

## How it was tested
Ran training with a dataset with `/` in the string. Confirmed not to error. 

Run all tests except `test_examples_3_and_2`. Passed.

## How to checkout & try?
Run training with a dataset with `/` in the string. E.g.:
```
python lerobot/scripts/train.py     policy=act     env=aloha     env.task=AlohaInsertion-v0     dataset_repo_id=lerobot/aloha_sim_insertion_human
```

2024-05-10 21:57 UTC, aliberts requested changes
Thank you! Minor suggestions, otherwise LTGM ;)

2024-05-10 21:57 UTC, aliberts commented on lerobot/common/logger.py
>          if self._wandb:
This should have probably already been there
```suggestion
        if self._wandb and not self._disable_wandb_artifact:
```
cc @Cadene to confirm this is what we'd want

2024-05-10 21:57 UTC, aliberts commented on lerobot/common/logger.py
> +                + str(identifier),
nit
```suggestion
                + f"-{self._seed}-{identifier}",
```

2024-05-10 21:57 UTC, aliberts commented on lerobot/common/logger.py
> +                    + str(identifier),
nit
```suggestion
                    + f"-{self._seed}-{identifier}",
```

2024-05-11 07:38 UTC, aliberts requested changes
Style is failing, should be good with this format (you can also make sure it will pass beforehand with `pre-commit run -a`)
Sorry for the back-and-forth ^^

2024-05-11 07:38 UTC, aliberts commented on lerobot/common/logger.py
> +                    + f"-{self._seed}-{identifier}",
```suggestion
                    f"{self._group.replace(':', '_').replace('/', '_')}-{self._seed}-{identifier}",
```

2024-05-11 07:38 UTC, aliberts commented on lerobot/common/logger.py
> +                + f"-{self._seed}-{identifier}",
```suggestion
                f"{self._group.replace(':', '_').replace('/', '_')}-{self._seed}-{identifier}",
```

2024-05-11 22:02 UTC, AshisGhosh commented
> Style is failing, should be good with this format (you can also make sure it will pass beforehand with `pre-commit run -a`) Sorry for the back-and-forth ^^

Whoops that's on me - happy to get it right.

2024-05-12 06:10 UTC, aliberts approved these changes
LGTM, thanks!

2024-05-12 06:13 UTC, merged