add EpisodeAwareSampler
huggingface/lerobot pull request #217
Opened 2024-05-28 08:23 UTC by radekosmulski

EpisodeAwareSampler allows the dropping of first n or last n frames from each episode.

Additionally, you can select which episodes to run on by passig in their ids (complements functionality of the hf dataset slice syntax to give extra flexibility to the user).

* modify train.py and diffusion.yaml to leverage new functionality and train on pusht with last 7 steps per episode dropped
* add unit tests

## What this does
resolves #129

## How it was tested
I ran the train script for diffusion and act. Also, I ran tests locally -- got some failures but I believe they are not related. Ran the unit tests I wrote.

## How to checkout & try? (for the reviewer)
Best to create a toy dataset and verify that `sampler.indices` reflect params passed to the constructor (like done in unit tests)

2024-05-28 08:53 UTC, radekosmulski commented
There is an end-to-end test failure that seems like it might be related, but the command executes fine on my machine:

```
(lerobot) radek@ubuntu-desktop:~/workspace/lerobot$ python lerobot/scripts/train.py \
        policy=act \
        policy.dim_model=64 \
        env=aloha \
        wandb.enable=False \
        training.offline_steps=2 \
        training.online_steps=0 \
        eval.n_episodes=1 \
        eval.batch_size=1 \
        device=cpu \
        training.save_model=true \
        training.save_freq=2 \
        policy.n_action_steps=20 \
        policy.chunk_size=20 \
        training.batch_size=2 \
        hydra.run.dir=tests/outputs/act/
WARNING 2024-05-28 18:50:33 ils/utils.py:42 Using CPU, this will be slow.
INFO 2024-05-28 18:50:33 ts/train.py:251 make_dataset
Fetching 56 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 9440.56it/s]
INFO 2024-05-28 18:50:41 ts/train.py:254 make_env
INFO 2024-05-28 18:50:41 /__init__.py:88 MUJOCO_GL is not set, so an OpenGL backend will be chosen automatically.
INFO 2024-05-28 18:50:41 /__init__.py:96 Successfully imported OpenGL backend: %s
INFO 2024-05-28 18:50:41 /__init__.py:31 MuJoCo library version is: %s
INFO 2024-05-28 18:50:41 ts/train.py:257 make_policy
INFO 2024-05-28 18:50:41 on/logger.py:66 Logs will be saved locally.
INFO 2024-05-28 18:50:41 on/logger.py:31 Output dir: tests/outputs/act/
INFO 2024-05-28 18:50:41 ts/train.py:272 cfg.env.task='AlohaInsertion-v0'
INFO 2024-05-28 18:50:41 ts/train.py:273 cfg.training.offline_steps=2 (2)
INFO 2024-05-28 18:50:41 ts/train.py:274 cfg.training.online_steps=0
INFO 2024-05-28 18:50:41 ts/train.py:275 offline_dataset.num_samples=17000 (17K)
INFO 2024-05-28 18:50:41 ts/train.py:276 offline_dataset.num_episodes=34
INFO 2024-05-28 18:50:41 ts/train.py:277 num_learnable_params=15096014 (15M)
INFO 2024-05-28 18:50:41 ts/train.py:278 num_total_params=15096104 (15M)
INFO 2024-05-28 18:50:41 ts/train.py:328 Start offline training on a fixed dataset
INFO 2024-05-28 18:50:42 ts/train.py:188 step:0 smpl:2 ep:0 epch:0.00 loss:71.398 grdn:743.832 lr:1.0e-05 updt_s:0.484
INFO 2024-05-28 18:50:42 ts/train.py:299 Checkpoint policy after step 2
INFO 2024-05-28 18:50:42 ts/train.py:308 Resume training
INFO 2024-05-28 18:50:42 ts/train.py:373 End of training
```

building the docker image for `make` to test, one thing that already stands out -- my local dataset has `offline_dataset.num_samples=17000 (17K)` 17k examples whereas the dataset the test runs on has only 500

2024-05-28 09:01 UTC, radekosmulski commented
Inside the docker container I executed `make test-end-to-end` and the first tests passes no problem, others tests are continuing to run.

But the test downloads the data and sees 17k examples. The test on github must be running on cached data, I assume, probably modified.

Maybe the dataset was sliced and so it doesn't have consecutive ids in hf_dataset['index']? Anyhow, will verify that the new functionality works with the slice API from `datasets`.

2024-05-28 09:06 UTC, radekosmulski commented
No issue running on a sliced dataset:

![image](https://github.com/huggingface/lerobot/assets/2444926/42cd731f-77c3-4f65-979b-424eaac65be4)

2024-05-28 09:21 UTC, radekosmulski commented
I pulled the data using `git lfs pull`, it is now in `test/data` locally on my machine, but when I run `make test-end-to-end` I am still (probably) running on downloaded data as there are 17k examples in the dataset

I saw @aliberts did a commit on fixing the nightly runs, so maybe he could shed some more light on what might be going on here :slightly_smiling_face: 

Any help would be greatly appreciated

2024-05-28 09:51 UTC, aliberts commented
> I pulled the data using `git lfs pull`, it is now in `test/data` locally on my machine, but when I run `make test-end-to-end` I am still (probably) running on downloaded data as there are 17k examples in the dataset

Hi there, yes you need to set the `DATA_DIR` environment variable before your command to use the test artifacts:
```bash
DATA_DIR=tests/data make test-end-to-end
```

2024-05-28 10:15 UTC, radekosmulski commented
hey @aliberts, thanks for the hint! :slightly_smiling_face: 

Turns out that when using cached data, the `episode_data_index` is inconsistent with the `index`.

This is the `index` on the hf_dataset:
```
[tensor(0), tensor(1), tensor(2), tensor(3), tensor(4), tensor(5), tensor(6), tensor(7), tensor(8), tensor(9), tensor(10), tensor(11), tensor(12), tensor(13), tensor(14), tensor(15), tensor(16), tensor(17), tensor(18), tensor(19), tensor(20), tensor(21), tensor(22), tensor(23), tensor(24), tensor(25), tensor(26), tensor(27), tensor(28), tensor(29), tensor(30), tensor(31), tensor(32), tensor(33), tensor(34), tensor(35), tensor(36), tensor(37), tensor(38), tensor(39), tensor(40), tensor(41), tensor(42), tensor(43), tensor(44), tensor(45), tensor(46), tensor(47), tensor(48), tensor(49), tensor(50), tensor(51), tensor(52), tensor(53), tensor(54), tensor(55), tensor(56), tensor(57), tensor(58), tensor(59), tensor(60), tensor(61), tensor(62), tensor(63), tensor(64), tensor(65), tensor(66), tensor(67), tensor(68), tensor(69), tensor(70), tensor(71), tensor(72), tensor(73), tensor(74), tensor(75), tensor(76), tensor(77), tensor(78), tensor(79), tensor(80), tensor(81), tensor(82), tensor(83), tensor(84), tensor(85), tensor(86), tensor(87), tensor(88), tensor(89), tensor(90), tensor(91), tensor(92), tensor(93), tensor(94), tensor(95), tensor(96), tensor(97), tensor(98), tensor(99), tensor(100), tensor(101), tensor(102), tensor(103), tensor(104), tensor(105), tensor(106), tensor(107), tensor(108), tensor(109), tensor(110), tensor(111), tensor(112), tensor(113), tensor(114), tensor(115), tensor(116), tensor(117), tensor(118), tensor(119), tensor(120), tensor(121), tensor(122), tensor(123), tensor(124), tensor(125), tensor(126), tensor(127), tensor(128), tensor(129), tensor(130), tensor(131), tensor(132), tensor(133), tensor(134), tensor(135), tensor(136), tensor(137), tensor(138), tensor(139), tensor(140), tensor(141), tensor(142), tensor(143), tensor(144), tensor(145), tensor(146), tensor(147), tensor(148), tensor(149), tensor(150), tensor(151), tensor(152), tensor(153), tensor(154), tensor(155), tensor(156), tensor(157), tensor(158), tensor(159), tensor(160), tensor(161), tensor(162), tensor(163), tensor(164), tensor(165), tensor(166), tensor(167), tensor(168), tensor(169), tensor(170), tensor(171), tensor(172), tensor(173), tensor(174), tensor(175), tensor(176), tensor(177), tensor(178), tensor(179), tensor(180), tensor(181), tensor(182), tensor(183), tensor(184), tensor(185), tensor(186), tensor(187), tensor(188), tensor(189), tensor(190), tensor(191), tensor(192), tensor(193), tensor(194), tensor(195), tensor(196), tensor(197), tensor(198), tensor(199), tensor(200), tensor(201), tensor(202), tensor(203), tensor(204), tensor(205), tensor(206), tensor(207), tensor(208), tensor(209), tensor(210), tensor(211), tensor(212), tensor(213), tensor(214), tensor(215), tensor(216), tensor(217), tensor(218), tensor(219), tensor(220), tensor(221), tensor(222), tensor(223), tensor(224), tensor(225), tensor(226), tensor(227), tensor(228), tensor(229), tensor(230), tensor(231), tensor(232), tensor(233), tensor(234), tensor(235), tensor(236), tensor(237), tensor(238), tensor(239), tensor(240), tensor(241), tensor(242), tensor(243), tensor(244), tensor(245), tensor(246), tensor(247), tensor(248), tensor(249), tensor(250), tensor(251), tensor(252), tensor(253), tensor(254), tensor(255), tensor(256), tensor(257), tensor(258), tensor(259), tensor(260), tensor(261), tensor(262), tensor(263), tensor(264), tensor(265), tensor(266), tensor(267), tensor(268), tensor(269), tensor(270), tensor(271), tensor(272), tensor(273), tensor(274), tensor(275), tensor(276), tensor(277), tensor(278), tensor(279), tensor(280), tensor(281), tensor(282), tensor(283), tensor(284), tensor(285), tensor(286), tensor(287), tensor(288), tensor(289), tensor(290), tensor(291), tensor(292), tensor(293), tensor(294), tensor(295), tensor(296), tensor(297), tensor(298), tensor(299), tensor(300), tensor(301), tensor(302), tensor(303), tensor(304), tensor(305), tensor(306), tensor(307), tensor(308), tensor(309), tensor(310), tensor(311), tensor(312), tensor(313), tensor(314), tensor(315), tensor(316), tensor(317), tensor(318), tensor(319), tensor(320), tensor(321), tensor(322), tensor(323), tensor(324), tensor(325), tensor(326), tensor(327), tensor(328), tensor(329), tensor(330), tensor(331), tensor(332), tensor(333), tensor(334), tensor(335), tensor(336), tensor(337), tensor(338), tensor(339), tensor(340), tensor(341), tensor(342), tensor(343), tensor(344), tensor(345), tensor(346), tensor(347), tensor(348), tensor(349), tensor(350), tensor(351), tensor(352), tensor(353), tensor(354), tensor(355), tensor(356), tensor(357), tensor(358), tensor(359), tensor(360), tensor(361), tensor(362), tensor(363), tensor(364), tensor(365), tensor(366), tensor(367), tensor(368), tensor(369), tensor(370), tensor(371), tensor(372), tensor(373), tensor(374), tensor(375), tensor(376), tensor(377), tensor(378), tensor(379), tensor(380), tensor(381), tensor(382), tensor(383), tensor(384), tensor(385), tensor(386), tensor(387), tensor(388), tensor(389), tensor(390), tensor(391), tensor(392), tensor(393), tensor(394), tensor(395), tensor(396), tensor(397), tensor(398), tensor(399), tensor(400), tensor(401), tensor(402), tensor(403), tensor(404), tensor(405), tensor(406), tensor(407), tensor(408), tensor(409), tensor(410), tensor(411), tensor(412), tensor(413), tensor(414), tensor(415), tensor(416), tensor(417), tensor(418), tensor(419), tensor(420), tensor(421), tensor(422), tensor(423), tensor(424), tensor(425), tensor(426), tensor(427), tensor(428), tensor(429), tensor(430), tensor(431), tensor(432), tensor(433), tensor(434), tensor(435), tensor(436), tensor(437), tensor(438), tensor(439), tensor(440), tensor(441), tensor(442), tensor(443), tensor(444), tensor(445), tensor(446), tensor(447), tensor(448), tensor(449), tensor(450), tensor(451), tensor(452), tensor(453), tensor(454), tensor(455), tensor(456), tensor(457), tensor(458), tensor(459), tensor(460), tensor(461), tensor(462), tensor(463), tensor(464), tensor(465), tensor(466), tensor(467), tensor(468), tensor(469), tensor(470), tensor(471), tensor(472), tensor(473), tensor(474), tensor(475), tensor(476), tensor(477), tensor(478), tensor(479), tensor(480), tensor(481), tensor(482), tensor(483), tensor(484), tensor(485), tensor(486), tensor(487), tensor(488), tensor(489), tensor(490), tensor(491), tensor(492), tensor(493), tensor(494), tensor(495), tensor(496), tensor(497), tensor(498), tensor(499)]
```

and this is the `episode_data_index`:

```
{'from': tensor([    0,   500,  1000,  1500,  2000,  2500,  3000,  3500,  4000,  4500,
         5000,  5500,  6000,  6500,  7000,  7500,  8000,  8500,  9000,  9500,
        10000, 10500, 11000, 11500, 12000, 12500, 13000, 13500, 14000, 14500,
        15000, 15500, 16000, 16500]), 'to': tensor([  500,  1000,  1500,  2000,  2500,  3000,  3500,  4000,  4500,  5000,
         5500,  6000,  6500,  7000,  7500,  8000,  8500,  9000,  9500, 10000,
        10500, 11000, 11500, 12000, 12500, 13000, 13500, 14000, 14500, 15000,
        15500, 16000, 16500, 17000])}
```

My assumption is that the dataset was either created with a version of `LeRobotDataset` before it supported the `datasets` slice syntax or the `LeRobotDataset` was modified post initialization before being saved.

Could the data generation be rerun with the current version of the lib? We probably shouldn't expect that the tests should pass with a malformed dataset. That does not only affect current functionality in this PR but might also affect future functionality.

The correct way to create a `LeRobotDataset` that would contain only the first 500 examples is as follows:
![image](https://github.com/huggingface/lerobot/assets/2444926/c9c059cc-1471-47b9-9b5d-d4aa118464b4)

Caching HuggingFace datasets is probably a good idea but caching (and not refreshing upon changes) a `LeRobotDat [...]

2024-05-28 11:20 UTC, alexander-soare requested changes
@radekosmulski I've left some comments in Reviewable (sorry to shake things up, but since you are a frequent contributor, it would be great if you could give it a try).
I think @Cadene may have some high level feedback as well. I'd suggest waiting for his thoughts before proceeding if that's okay.

> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217#-:-NyyuooR1q8thp2AGqM9:b-fcngga)* status: Some CI tests are either incomplete or have failed!, 0 of 4 files reviewed, 3 unresolved discussions (waiting on @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-NyyudbP085eWJ8uXS72:bb3erx6) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
> ```Python
>         indices = []
>         for episode_idx, (start_index, end_index) in enumerate(
>             zip(episode_data_index["from"], episode_data_index["to"], strict=False)
> ```

Why strict=False? I think we should expect that these iterables have the same length.
___
*[`lerobot/scripts/train.py` line 315 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyugXV6S2IW1Ic5pVc:-NyyugXV6S2IW1Ic5pVd:b-1gqkpe) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/scripts/train.py#L315)):*
> ```Python
>         num_workers=4,
>         batch_size=cfg.training.batch_size,
>         sampler=EpisodeAwareSampler(
> ```

I like having the ability to use `shuffle=False` for debugging and it's not immediately clear to me how I can do that while still using the the functionality provided by the `EpisodeAwareSampler`. Can we build in a shuffle option?
___
*[`tests/test_sampler.py` line 36 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyujpL6YnxtLvOPrLC:-NyyujpL6YnxtLvOPrLD:b-ftrz0j) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/tests/test_sampler.py#L36)):*
> ```Python
>     episode_data_index = calculate_episode_data_index(dataset)
>     sampler = EpisodeAwareSampler(episode_data_index, drop_n_first_frames=1)
>     assert sampler.indices == [1, 4, 5]
> ```

Is there any way we can tests the output of the API rather than the internals? (ie put iterate through it and make sure we get the indices we want and nothing else, and also check that len() gives us what we should expect).

Ditto below.


<!-- Sent from Reviewable.io -->

2024-05-28 12:14 UTC, radekosmulski reviewed
sure thing, sounds great! :raised_hands: 

> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217#-:-NyywhCgDP-r_R6cgIs8:b1nn381)* status: Some CI tests are either incomplete or have failed!, 0 of 4 files reviewed, 3 unresolved discussions (waiting on @alexander-soare)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-Nyywtkq0j0wnwdN5VDl:b-hy49f3) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Why strict=False? I think we should expect that these iterables have the same length.
</blockquote></details>

yeah I wonder how this ended up there... I am thinking it might have been one of the formatters/linters? I will pay more attention to this going forward as I am quite convinced I didn't put this there myself (EDIT: yup, just confirmed, it is coming from one of formatters)

maybe the "best practice" in post python 3.10 world is to always set it to either True or False, for it to be explicit? but I 100% agree with you -- `strict=False` doesn't make sense, `strict=True` is probably what we want to have here
___
*[`lerobot/scripts/train.py` line 315 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyugXV6S2IW1Ic5pVc:-Nyz2dpG1HHjNJXlmHj-:b-5lvoo0) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/scripts/train.py#L315)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

I like having the ability to use `shuffle=False` for debugging and it's not immediately clear to me how I can do that while still using the the functionality provided by the `EpisodeAwareSampler`. Can we build in a shuffle option?
</blockquote></details>

Added `shuffle=False` and dropped inheriting from `RandomSubsetSampler` as that probably doesn't make sense anymore
___
*[`tests/test_sampler.py` line 36 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyujpL6YnxtLvOPrLC:-Nyz2rVo3i4qgJ7Qw8rE:bb7f2mf) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/tests/test_sampler.py#L36)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Is there any way we can tests the output of the API rather than the internals? (ie put iterate through it and make sure we get the indices we want and nothing else, and also check that len() gives us what we should expect).

Ditto below.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-05-28 12:50 UTC, alexander-soare requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 3 unresolved discussions (waiting on @aliberts and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-NyzDSNKD078XhrommtE:b-o43bzs) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, radekosmulski (Radek Osmulski) wrote…</i></summary><blockquote>

yeah I wonder how this ended up there... I am thinking it might have been one of the formatters/linters? I will pay more attention to this going forward as I am quite convinced I didn't put this there myself (EDIT: yup, just confirmed, it is coming from one of formatters)

maybe the "best practice" in post python 3.10 world is to always set it to either True or False, for it to be explicit? but I 100% agree with you -- `strict=False` doesn't make sense, `strict=True` is probably what we want to have here
</blockquote></details>

cc @aliberts. I've corrected quite a few of these. Can we do something about it?
___
*[`lerobot/common/datasets/sampler.py` line 28 at r2](https://reviewable.io/reviews/huggingface/lerobot/217#-NyzEWCp0YDknBcLjBd5:-NyzEWCp0YDknBcLjBd6:bk3b48n) ([raw file](https://github.com/huggingface/lerobot/blob/d72916ebe27a4f42a4a3b2b198cc67d86f04e000/lerobot/common/datasets/sampler.py#L28)):*
> ```Python
>         drop_n_first_frames: int = 0,
>         drop_n_last_frames: int = 0,
>         shuffle: bool = True,
> ```

Can we please default this to the same as the dataloader? I think this should be minimally disruptive.
___
*[`lerobot/scripts/train.py` line 315 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyugXV6S2IW1Ic5pVc:-NyzELN46Ay9mAz9lPXj:b-hh0wj5) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/scripts/train.py#L315)):*
<details><summary><i>Previously, radekosmulski (Radek Osmulski) wrote…</i></summary><blockquote>

Added `shuffle=False` and dropped inheriting from `RandomSubsetSampler` as that probably doesn't make sense anymore
</blockquote></details>

Lovely. Then just a nit to be explicit about that kwarg here, same as the prior state.
___
*[`tests/test_sampler.py` line 36 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyujpL6YnxtLvOPrLC:-NyzF1Aw3wYdEtLjCv29:b4ezx10) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/tests/test_sampler.py#L36)):*
<details><summary><i>Previously, radekosmulski (Radek Osmulski) wrote…</i></summary><blockquote>

done
</blockquote></details>

Eloquent :) Thank you


<!-- Sent from Reviewable.io -->

2024-05-28 13:16 UTC, radekosmulski reviewed
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alexander-soare and @aliberts)

___
*[`lerobot/common/datasets/sampler.py` line 28 at r2](https://reviewable.io/reviews/huggingface/lerobot/217#-NyzEWCp0YDknBcLjBd5:-NyzJS5MEkIKgZp3oZbi:b-2cxlxz) ([raw file](https://github.com/huggingface/lerobot/blob/d72916ebe27a4f42a4a3b2b198cc67d86f04e000/lerobot/common/datasets/sampler.py#L28)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Can we please default this to the same as the dataloader? I think this should be minimally disruptive.
</blockquote></details>

sure thing, change made
___
*[`lerobot/scripts/train.py` line 315 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyugXV6S2IW1Ic5pVc:-NyzJl6p-TjSCeAHIoGO:b-66q1an) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/scripts/train.py#L315)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Lovely. Then just a nit to be explicit about that kwarg here, same as the prior state.
</blockquote></details>

makes sense, explicit is the way to go :slightly_smiling_face: 
___
*[`tests/test_sampler.py` line 36 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyujpL6YnxtLvOPrLC:-NyzJujE4jEzmzx1d2IC:buhmx4x) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/tests/test_sampler.py#L36)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Eloquent :) Thank you
</blockquote></details>

:smile: :pray: 


<!-- Sent from Reviewable.io -->

2024-05-28 13:37 UTC, alexander-soare reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, 2 of 4 files reviewed, 2 unresolved discussions (waiting on @aliberts and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 30 at r4](https://reviewable.io/reviews/huggingface/lerobot/217#-NyzP_-c3sHyZH1O6mt7:-NyzP_-c3sHyZH1O6mt8:bdv5ag6) ([raw file](https://github.com/huggingface/lerobot/blob/d5d8d6f529e48fe8424e22bff9e59184e06f68bc/lerobot/common/datasets/sampler.py#L30)):*
> ```Python
>         shuffle: bool = False,
>     ):
>         """Sampler that optionally incorporates episode boundary information.
> ```

nit: We haven't agreed on this officially but let's stick with what most of the code base is doing for docstrings. Two changes please:

1. Remove type hinting from the docstring
2. Remove "defaults to..." (unless there needs to be a non-obvious explanation about what the default value means).

The reasoning is to not have duplication that becomes harder to maintain.


<!-- Sent from Reviewable.io -->

2024-05-28 13:38 UTC, alexander-soare approved these changes
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @aliberts and @radekosmulski)



<!-- Sent from Reviewable.io -->

2024-05-28 16:02 UTC, alexander-soare approved these changes
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @aliberts and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-Nyzvc83AVoabmC9Xopw:bq85c5b) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, aliberts (Simon Alibert) wrote…</i></summary><blockquote>

Yes, having an explicit `strict` argument in zips is enforced by one of our linter rules ([B905](https://docs.astral.sh/ruff/rules/zip-without-explicit-strict/)). However, it's up to the dev to choose whether it is `True` or `False`. If the lengths of the two iterables should alway be equal, `strict` should be set to `True` as `False` will fail silently.
</blockquote></details>

@aliberts it seems @radekosmulski is saying that it somehow automatically selects `False` for him (and I think he just staged the change without noticing it). Is it possible to make it not automatically resolve the problem? Btw this is not urgent. Just saying as I had to fix a few of these in the code so I'm assuming it happened many times to people.


<!-- Sent from Reviewable.io -->

2024-05-28 16:02 UTC, alexander-soare approved these changes
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @aliberts and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-Nyzw3l48XBLexzNJnvz:b-ynjua6) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

@aliberts it seems @radekosmulski is saying that it somehow automatically selects `False` for him (and I think he just staged the change without noticing it). Is it possible to make it not automatically resolve the problem? Btw this is not urgent. Just saying as I had to fix a few of these in the code so I'm assuming it happened many times to people.
</blockquote></details>

Moving this to Discord.


<!-- Sent from Reviewable.io -->

2024-05-28 16:03 UTC, alexander-soare approved these changes
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @aliberts and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-NyzwFYx52MFAa3s5meC:b-o3cxa1) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

Moving this to Discord.
</blockquote></details>

When I get Radek to accept my friend request...


<!-- Sent from Reviewable.io -->

2024-05-28 18:28 UTC, aliberts reviewed
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @alexander-soare and @radekosmulski)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-Nz-Rji24N62ksJs1mIi:blvxbyn) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

When I get Radek to accept my friend request...
</blockquote></details>

Oh yes sorry. It's weird because I remember this not being auto-fixed by the formatter, but I just tried it now and indeed it defaults to writing `strict=False` if there's no `strict` argument. I'll see how we can set it up so that it raises an error but doesn't auto fix (which is what we want I think). Thanks for noticing!


<!-- Sent from Reviewable.io -->

2024-05-28 22:15 UTC, radekosmulski reviewed
ty! 

> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217#-:-Nz0E1dk6HaEABOUHU9L:bb7pfxl)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 2 unresolved discussions (waiting on @alexander-soare and @aliberts)

___
*[`lerobot/common/datasets/sampler.py` line 40 at r1](https://reviewable.io/reviews/huggingface/lerobot/217#-NyyudbP085eWJ8uXS71:-Nz0EvLKC3dq-thMy6_e:brod38m) ([raw file](https://github.com/huggingface/lerobot/blob/d4cda27060bedee18b8405960822134bee53eb30/lerobot/common/datasets/sampler.py#L40)):*
<details><summary><i>Previously, aliberts (Simon Alibert) wrote…</i></summary><blockquote>

Oh yes sorry. It's weird because I remember this not being auto-fixed by the formatter, but I just tried it now and indeed it defaults to writing `strict=False` if there's no `strict` argument. I'll see how we can set it up so that it raises an error but doesn't auto fix (which is what we want I think). Thanks for noticing!
</blockquote></details>

ah yes, sorry, not a major discord user, all accepted now :slightly_smiling_face: 
___
*[`lerobot/common/datasets/sampler.py` line 30 at r4](https://reviewable.io/reviews/huggingface/lerobot/217#-NyzP_-c3sHyZH1O6mt7:-Nz0E51eEiP_H4y43fTW:b-dsvegb) ([raw file](https://github.com/huggingface/lerobot/blob/d5d8d6f529e48fe8424e22bff9e59184e06f68bc/lerobot/common/datasets/sampler.py#L30)):*
<details><summary><i>Previously, alexander-soare (Alexander Soare) wrote…</i></summary><blockquote>

nit: We haven't agreed on this officially but let's stick with what most of the code base is doing for docstrings. Two changes please:

1. Remove type hinting from the docstring
2. Remove "defaults to..." (unless there needs to be a non-obvious explanation about what the default value means).

The reasoning is to not have duplication that becomes harder to maintain.
</blockquote></details>

I am all for DRY, sounds great :slightly_smiling_face: Change made


<!-- Sent from Reviewable.io -->

2024-05-29 06:39 UTC, alexander-soare reviewed
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, 3 of 4 files reviewed, all discussions resolved

___
*[`lerobot/common/datasets/sampler.py` line 30 at r4](https://reviewable.io/reviews/huggingface/lerobot/217#-NyzP_-c3sHyZH1O6mt7:-Nz23iG3BUiN_YIsEY7L:bgc7vqv) ([raw file](https://github.com/huggingface/lerobot/blob/d5d8d6f529e48fe8424e22bff9e59184e06f68bc/lerobot/common/datasets/sampler.py#L30)):*
<details><summary><i>Previously, radekosmulski (Radek Osmulski) wrote…</i></summary><blockquote>

I am all for DRY, sounds great :slightly_smiling_face: Change made
</blockquote></details>

:heart: 


<!-- Sent from Reviewable.io -->

2024-05-29 21:49 UTC, radekosmulski commented on lerobot/common/datasets/sampler.py
> +#!/usr/bin/env python
thank you very much for your kind words! :slightly_smiling_face: very glad I could be of help

2024-05-30 08:03 UTC, alexander-soare approved these changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/huggingface/lerobot/217)* status: Some CI tests are either incomplete or have failed!, all files reviewed, 3 unresolved discussions (waiting on @Cadene and @radekosmulski)



<!-- Sent from Reviewable.io -->

2024-05-31 03:50 UTC, radekosmulski commented
cc @alexander-soare @alexander-soare

I found an issue in the train.py of this PR (the `cfg.get("drop_n_last_frame")` was referencing a key that -- if it would be defined -- would be on `cft.training`), will fix it here in a second.

But more broadly, I took a look at how OmegaConf interprets the values and came across our use of `eval`. But I thought that maybe this additional context can be helpful so sharing it here:

The current value in `diffusion.yml`:
```
drop_n_last_frames: ${policy.horizon} - ${policy.n_action_steps} - ${policy.n_obs_steps} + 1
```
becomes a string when read
![image](https://github.com/huggingface/lerobot/assets/2444926/274852bf-1aad-4ef9-9199-8ff186bb98b0)

This is problematic because:
* we have to then `eval` it in Python
* it is sort of misleading to the user -- I mean, this reads as something that one would expect gets evaluated to a number, but as it turns out there is no arithmetic in OmegaConf

So I dug a bit and thought that maybe a custom resolver would be the way to go:
![image](https://github.com/huggingface/lerobot/assets/2444926/81cc343c-58e3-43bf-859b-22aa13e3549c)

This works, but problem here is that we need to have this illegible entry in conf:
```
drop_n_last_frames: ${drop_n_last_frames:${policy.horizon},${policy.n_action_steps},${policy.n_obs_steps}}
```
So this is not great either.

I came to the conclusion that possibly using static entries might be best:
```
drop_n_last_frames: 7  # ${policy.horizon} - ${policy.n_action_steps} - ${policy.n_obs_steps} + 1
```
The pseudo-code tells the user where this value comes from. We probably don't want this value to be calculated on the fly.

I mean -- none of the other values in the config are. When someone changes their `batch_size`, we don't modify the `lr`, etc.

I went with this approach for this PR, but if you would have a different take on this, please let me know!

2024-05-31 09:36 UTC, alexander-soare commented
@radekosmulski I think your idea of using static entries for `drop_n_last_frames` is good. Waiting on @Cadene regarding that, and I've automatically updated your branch. Then we can hopefully merge :)

2024-05-31 12:07 UTC, Cadene commented on lerobot/scripts/train.py
> +        sampler = None
What do you think?
```suggestion
    if cfg.training.get("drop_n_last_frames", False):   # should be a boolean value
        shuffle = False
        num_last_frames_to_drop = cfg.policy.horizon - cfg.policy.n_action_steps - cf.gpolicy.n_obs_steps + 1
        sampler = EpisodeAwareSampler(
            offline_dataset.episode_data_index,
            num_last_frames_to_drop=num_last_frames_to_drop,
            shuffle=True,
        )
    else:
        shuffle = True
        sampler = None
```

2024-05-31 12:18 UTC, Cadene commented on lerobot/scripts/train.py
> +        sampler = None
It seems static is our best option as of now.

2024-05-31 12:43 UTC, merged