Adapting to thom arm
huggingface/lerobot pull request #221
Opened 2024-05-29 09:43 UTC by thomwolf

1. first commit: make push_to_hub less hardcoded (cf https://discord.com/channels/1216765309076115607/1245029082266206251/12450445273839739590
2. adapt aloha_dora to be able to use more general camera setups

2024-05-29 10:14 UTC, Cadene requested changes

2024-05-29 10:14 UTC, Cadene commented on lerobot/common/datasets/push_dataset_to_hub/aloha_dora_format.py
> +    reference_key = reference_files[0].stem
```suggestion
    # select first camera in alphanumeric order
    reference_key = sorted(reference_files)[0].stem
```

2024-05-29 10:14 UTC, Cadene commented on lerobot/scripts/push_dataset_to_hub.py
> +        help="Root directory containing input raw datasets (e.g. `data` or `tmp/data` or `/tmp/lerobot/data`).",
What do you think of this API?
```suggestion
        help="Directory containing input raw datasets (e.g. `data/aloha_mobile_chair_raw` or `data/pusht_raw`).",
```

2024-06-05 22:17 UTC, radekosmulski commented
regarding the staggering issue of the robot arm as in the recorded episode that can be watched as follows: `python lerobot/scripts/visualize_dataset.py --repo-id radek/place_in_bowl2 --episode-index 0` (while recording, the arm staggers and doesn't move smoothly, in recording it moves instantaneously)

* I updated firmware on all the dynamixel servos and went through the config to align positions using homing offset
* tested this directly with teleop from Alex's repo, no issue
* ran with lower fps -- 10 fps, issue persists
* removed camera from config -- issue goes away, but recording happens extremely fast! according to the progress bar, the recording happens at 90 - 130 fps, the episode doesn't last the usual 12+ seconds (400/30) but the recording completes much quicker
* when running with camera, the reported fps was < 30, around 28.4

2024-06-12 19:51 UTC, closed without merging