Add UFACTORY 850 as one of the robots supported, introduce various HRI utilities for teleop and next episode hinting while reseting
huggingface/lerobot pull request #493
Opened 2024-10-28 12:38 UTC by vmayoral

This PR comes as a result of the Oct 2024 Hackathon wherein I participated remotely. Results were successful within the weekend of hacking, so I thought I'd give back and contribute. Results first:

- [Setup with basic HRI for teleop](https://github.com/user-attachments/assets/5778900f-1e9d-4120-9f51-02d8acad3694)
- [`lerobot` teleop operational in UFACTORY 850](https://github.com/user-attachments/assets/aea3ac90-5b0b-4009-8dd6-047d6d7c800f)
- [Moving jellyfish grasped, `top`](https://github.com/user-attachments/assets/65699102-c78e-444c-8e85-6e738101e628)
- [Moving jellyfish grasped, `wrist`](https://github.com/user-attachments/assets/0a4a1a16-ad14-4058-ac77-1cbadb8a2753)

| resulting dataset |  resulting policy |
|-----|-----|
| https://huggingface.co/datasets/vmayoral/u850_test | https://huggingface.co/vmayoral/act_u850_test |

The contributions of this PR are summarized below:
- Add UFACTORY 850 as one of the supported robots, validing principles and introducing support for a commercial-grade *lowcost* cobot solution
- Enabled teleop while reseting episode 
- Various minor updates for usability including next episode dislosure while reseting
- Ensures datatypes are consistent across realsense camera instantiations
- Proposes a generic `xArmWrapper` of the UFACTORY Python SDK, usable with other arms from the same vendor
- extends `manipulator.py` with *minimal* changes (attempted respecting the already existing structure) to support the new arm tested
- Configs and related minor changes

Some notes and considerations:
- Current teleop mechanism in UFACTORY is jerky when compared to simpler implementations. There's plenty of margin for improvement here. Let me know if this of interest and I may find some room for contributing here as well.
- It'd be fantastic to get some recommendations concerning how to collect the dataset episodes, specially in terms of variability of samples for generalization. For those of us not so *atuned* to the subtleties of ACT, these recommendations would be extremely valuable.

2024-10-31 15:45 UTC, Cadene commented
Wow really cool! We are in the middle of a refactor. We will come back to this PR soon. In the meantime, I am curious if other people working on UFACTORY 850 are able to use this arm with LeRobot :)

2024-11-04 04:56 UTC, vmayoral commented
Let me know @Cadene if you'd like other flavours of xArm robots tested. I'm rather certain it will, as the UFACTORY API is rather well structured and known reproducible. I've got an `xArm Lite 6` also lying around, happy to test it if that gets this PR moving forward.

2024-11-04 16:04 UTC, Cadene commented
@vmayoral Sounds good ;) Any chance you could run `pre-commit run --all-files`?
See: https://github.com/huggingface/lerobot/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr
Thanks 🙏

2024-11-07 19:34 UTC, apockill requested changes

2024-11-07 19:34 UTC, apockill commented on lerobot/common/robot_devices/robots/manipulator.py
> +                if self.robot_type == "u850":
This approach of adding if/elif throughout the codebase doesn't seem scalable.

What do folks think about creating an abstract base class that all robots can implement their wrapper API's within, so we don't have to edit so much code in a brittle way to add new robot support?

I can take this on- I'm currently working on adding support for the elephant robotics MyArmM&C series.

2024-11-11 16:45 UTC, apockill commented on lerobot/common/robot_devices/robots/manipulator.py
> +                if self.robot_type == "u850":
Okay, sounds good! Maybe let's keep things as is, once xarm / myarm support is merged in I can jump in and write wrappers for all the currently supported robots.

The only hard thing will just be to have everyone test their bots out for regressions.

2024-11-17 15:53 UTC, vmayoral commented
> @vmayoral Sounds good ;) Any chance you could run `pre-commit run --all-files`? See: https://github.com/huggingface/lerobot/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr Thanks 🙏

@Cadene all ready concerning these requests. Should be good to go as of right now. Just rebased on top of `main`.

2024-11-19 09:49 UTC, vmayoral commented
Ping @Cadene and team. Let me know if you folks require anything else.

2024-11-25 09:51 UTC, vmayoral commented
Friendly ping @Cadene. Let me know if you're missing anything.

2025-03-28 16:55 UTC, srisaripalli commented
> 
> Some notes and considerations:
> 
>     * Current teleop mechanism in UFACTORY is jerky when compared to simpler implementations. There's plenty of margin for improvement here. Let me know if this of interest and I may find some room for contributing here as well.

@vmayoral  Thank you for this! We got the entire thing working on two xARM 850's. As you mentioned the teleop is quite jerky via control_robot.py or the 1_teleop_lerobot. Any idea(s) on where we should look to fix this?

2025-03-28 20:29 UTC, vmayoral commented
A few:
- implement a filter, that did it mostly for me
- don’t use default configs of the robot, instead leverage restricted degrees/s configs
- ensure proper setup conditions

curious about your use case. Feel free to reach out and if you can elaborate more on your use, happy to find some time and help.

2025-03-28 21:08 UTC, srisaripalli commented
> A few:
> 
>     * implement a filter, that did it mostly for me
> 
>     * don’t use default configs of the robot, instead leverage restricted degrees/s configs
> 
>     * ensure proper setup conditions
> 
> 
> curious about your use case. Feel free to reach out and if you can elaborate more on your use, happy to find some time and help.

Currently just trying to figure out if we can use an xARM 850 in an imitation learning framework (btw cool office:-)). If we get it working, we want to use both xARM's to move things around in a home like environment (dual arm config). Commenting out the max_relative_target seems to make the teleop OK but then replay still has issues.... Short video of replaying an episode here (https://youtube.com/shorts/Fzs2_MnPVe0)

2025-10-06 17:32 UTC, imstevenpmwork commented
I think this would be a great opportunity to test this new feature: https://github.com/huggingface/lerobot/pull/2123

2026-08-04 15:40 UTC, imstevenpmwork commented
Thank you for this hackathon contribution and the detailed demos. The PR targets the old robot_devices/manipulator.py + yaml-config + control_robot.py stack, all of which was removed in the Hardware API redesign (#777, e23b41e79) and config simplification (#550) — 12 of the 14 touched files no longer exist on main, and the HRI hints were patched into that deleted control loop (main now has voice announcements via log_say in lerobot-record). The way to bring UFACTORY 850 support today is a lerobot_robot_ufactory plugin package (docs/source/integrate_hardware.mdx, enabled by #2123) or a Robot subclass PR against the new API. Closing as obsolete — a rewrite as a plugin would be very welcome.

2026-08-04 15:40 UTC, closed without merging