fixes to SO-100 readme
huggingface/lerobot pull request #600
Opened 2024-12-27 02:38 UTC by philfung

## What this does
Fixes to the S0-100 instructions

- Mac: added Mac-specific instructions.  the previous instructions were only for Ubuntu
- readability: increased readability by using numbered lists and sublists (see below for before/after)
- links: links to youtube videos are to the exact sections of the video instead of to the start

## How it was tested
- looked through README, made sure instructions made sense for both ubuntu and Mac
- I ran through and made the entire arm with a Mac using the README instructions

Possible reviewers: @jess-moss @Cadene @aliberts 

## before
<img width="871" alt="Screenshot 2024-12-26 at 6 35 56 PM" src="https://github.com/user-attachments/assets/b18e7b9b-6f1a-43bf-b254-7bdb752c25c5" />

## after
<img width="609" alt="Screenshot 2024-12-26 at 6 35 15 PM" src="https://github.com/user-attachments/assets/afeb73dc-1a55-4ea1-9292-76fe5cd27a9c" />

2025-01-04 17:16 UTC, philfung commented
Hi!  Quick ping to see if you are willing to merge this?  It's a low-risk doc change and just trying to make your documentation better for others : ) .  Thanks in any case!

2025-01-09 08:56 UTC, aliberts requested changes
Thank you!
Suggested a few more changes to improve it a bit more and you're good to merge ;)

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +2. Restart shell or `source ~/.bashrc` (*Mac*: `source ~/.bash_profile`)
```suggestion
2. Restart shell or `source ~/.bashrc` (*Mac*: `source ~/.bash_profile`) or `source ~/.zshrc` if you're using zshell
```

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +Follow step 2 of the [assembly video](https://youtu.be/FioA2oeFZ5I?si=-BQrBj4IUId8YgJE&t=248). You need to remove the gear for the motors of the leader arm. As a result, you will only use the positio
We can remove those session trackers
```suggestion
Follow step 2 of the [assembly video](https://youtu.be/FioA2oeFZ5I?t=248). You need to remove the gear for the motors of the leader arm. As a result, you will only use the position encoding of the motor and reduce friction to more easily operate the leader arm.
```

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +Follow step 3 of the [assembly video](https://youtu.be/FioA2oeFZ5I?si=HGI7n48G2iA9409m&t=569). For SO-100, you need to align the holes on the motor horn to the motor spline to be approximately 1:30,
```suggestion
Follow step 3 of the [assembly video](https://youtu.be/FioA2oeFZ5I?t=569). For SO-100, you need to align the holes on the motor horn to the motor spline to be approximately 1:30, 4:30, 7:30 and 10:30.
```

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +Follow step 4 of the [assembly video](https://youtu.be/FioA2oeFZ5I?si=nlqJG6KOMfkN8yfy&t=610). The first arm should take a bit more than 1 hour to assemble, but once you get use to it, you can do it
```suggestion
Follow step 4 of the [assembly video](https://youtu.be/FioA2oeFZ5I?t=610). The first arm should take a bit more than 1 hour to assemble, but once you get use to it, you can do it under 1 hour for the second arm.
```

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +/!\ Contrarily to step 6 of the [assembly video](https://youtu.be/FioA2oeFZ5I?si=w3EoJU6mu-DezXuo&t=724) which illustrates the auto calibration, we will actually do manual calibration of follower for
```suggestion
/!\ Contrarily to step 6 of the [assembly video](https://youtu.be/FioA2oeFZ5I?t=724) which illustrates the auto calibration, we will actually do manual calibration of follower for now.
```

2025-01-09 08:56 UTC, aliberts commented on examples/10_use_so100.md
> +Follow step 6 of the [assembly video](https://youtu.be/FioA2oeFZ5I?si=w3EoJU6mu-DezXuo&t=724) which illustrates the manual calibration. You will need to move the leader arm to these positions sequent
```suggestion
Follow step 6 of the [assembly video](https://youtu.be/FioA2oeFZ5I?t=724) which illustrates the manual calibration. You will need to move the leader arm to these positions sequentially:
```

2025-01-10 02:48 UTC, philfung commented
thanks @aliberts - applied all your suggested changes in https://github.com/huggingface/lerobot/pull/600/commits/adb5b76a0b03007fa51fe0c235599b0e4596f1ab.  Appreciate reviewing and lmk if anything else!

2025-01-10 10:29 UTC, aliberts approved these changes

2025-01-10 10:30 UTC, merged